- apiGroups:
    - ""
  resources:
    - configmaps
    - persistentvolumeclaims
    - secrets
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - endpoints
    - pods
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - apps
  resources:
    - statefulsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - cluster.redpanda.com
  resources:
    - redpandas
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - cluster.redpanda.com
  resources:
    - redpandas/finalizers
  verbs:
    - update
- apiGroups:
    - cluster.redpanda.com
  resources:
    - redpandas/status
  verbs:
    - get
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.openeverest.io
  resources:
    - instances
    - providers
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.openeverest.io
  resources:
    - instances/status
  verbs:
    - get
    - patch
    - update
